### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Molnfront** [RajarsiGit/Login-System-using-Face-Recognition#1]
Hi,
I was curious and tried your app at https://face-rec-login.herokuapp.com/.

But after entering e mail and submitting the data I got Internal Server Error

**Comment by Molnfront** [comment]
It works! I started with the login screen first. You have to type in the register URL. I understand that it just has a basic UI. But I found out how it works after checking the code.

**Comment by stephenmatthews** [comment]
Hi @Molnfront,

How did you fix this error? I'm getting the same issue when a user that isn't registered tries to login.

**Comment by Molnfront** [comment]
@stephenmatthews You have to type in the register URL!
